/*!CK:3732554774!*//*1453403710,*/

if (self.CavalryLogger) { CavalryLogger.start_js(["gBP8x"]); }

__d('InsightsInfoTip.react',['Image.react','React','ReactDOM','Tooltip','cx','ix','joinClasses'],function a(b,c,d,e,f,g,h,i,j,k,l,m,n){if(c.__markCompiled)c.__markCompiled();var o=i.PropTypes,p=i.createClass({displayName:'InsightsInfoTip',propTypes:{alignH:o.oneOf(['center','left','right']),position:o.oneOf(['above','below','left','right'])},getDefaultProps:function(){return {alignH:'right',position:'above'};},_setTooltip:function(){k.set(j.findDOMNode(this.refs.root),j.findDOMNode(this.refs.tooltip).cloneNode(true),this.props.position,this.props.alignH);},componentDidMount:function(){this._setTooltip();},componentDidUpdate:function(q){this._setTooltip();},componentWillUnmount:function(){if(this.refs.icon)k.remove(j.findDOMNode(this.refs.icon));},render:function(){var q=m('/images/hubble/info/info-flat_s.png'),r=null;if(!this.props.noImage)r=i.createElement(h,{className:"_5j1g",src:q,ref:'icon'});var s=n("_5j1f",this.props.className);return (i.createElement('span',{className:s,ref:'root'},this.props.children,r,i.createElement('div',{className:"_5j1h"},i.createElement('div',{className:"_5j1i",ref:'tooltip'},this.props.tip))));}});f.exports=p;},null);
__d('InsightsLegendKey.react',['React','cx','joinClasses'],function a(b,c,d,e,f,g,h,i,j){if(c.__markCompiled)c.__markCompiled();var k=h.createClass({displayName:'InsightsLegendKey',render:function(){if(this.props.children.length!==2)return;var l=j("_kz-",this.props.className);return (h.createElement('div',{className:l},this.props.children[0],h.createElement('span',{className:"_kdk"},this.props.children[1])));}});f.exports=k;},null);
__d('InsightsLegend_DEPRECATED.react',['React','cx','joinClasses'],function a(b,c,d,e,f,g,h,i,j){if(c.__markCompiled)c.__markCompiled();var k=h.createClass({displayName:'InsightsLegend',render:function(){var l=this.props.layout||k.layout.FLOATED,m=j("_1ovd"+(l==k.layout.FLOATED?' '+"_1ove":''),this.props.className);return (h.createElement('div',{className:m},this.props.children));}});k.layout={FLOATED:'floated',STACKED:'stacked'};f.exports=k;},null);
__d('formatNumber',['intlNumUtils'],function a(b,c,d,e,f,g,h){if(c.__markCompiled)c.__markCompiled();function i(){for(var j=arguments.length,k=Array(j),l=0;l<j;l++)k[l]=arguments[l];return h.formatNumber.apply(h,k);}i.withThousandDelimiters=h.formatNumberWithThousandDelimiters;f.exports=i;},null);
__d('art/modes/current',[],function a(b,c,d,e,f,g){if(c.__markCompiled)c.__markCompiled();function h(){throw new Error('You must require a mode before requiring anything else.');}g.Surface=h;g.Path=h;g.Shape=h;g.Group=h;g.ClippingRectangle=h;g.Text=h;g.setCurrent=function(i){for(var j in i)g[j]=i[j];};},null);
__d('BUIInsightsChartLegend.react',['immutable','InsightsChartLegend.react','React','ReactComponentWithPureRenderMixin','invariant','BUIInsightsTheme'],function a(b,c,d,e,f,g,h,i,j,k,l){'use strict';if(c.__markCompiled)c.__markCompiled();var m=h.Map,n=j.createClass({displayName:'ChartLegend',mixins:[k],propTypes:babelHelpers._extends({},i.propTypes),render:function(){var o=c('BUIInsightsTheme'),p=this.props,q=p.chart,r=p.items,s=this.props.schema||q.props.schema,t=o.colors.merge(q.props.colors),u=Array.from(t.keys());!(r.size<=u.length)?l(0):undefined;var v=0,w=m().withMutations(function(x){r.forEach(function(y){if(y.key in s)x.set(y.key,t.get(u[v++]));});});q=j.cloneElement(q,{autoColors:w});return (j.createElement(i,babelHelpers._extends({},this.props,{chart:q}),this.props.children));}});f.exports=n;},null);
__d('LineClamp.react',['React','Locale','cx','getVendorPrefixedName','joinClasses'],function a(b,c,d,e,f,g,h,i,j,k,l){'use strict';if(c.__markCompiled)c.__markCompiled();var m=h.PropTypes,n=k('lineClamp'),o=h.createClass({displayName:'LineClamp',propTypes:{customEllipsis:m.node,disableNative:m.bool,lineHeight:m.number,lines:m.number.isRequired},_renderEllipsis:function(){var p;if(this.props.lineHeight)p={bottom:this.props.lineHeight+'px'};var q=i.isRTL()?"_4ik3 _2k5c":"_4ik3 _2k5d";return (h.createElement('div',{style:p,className:q,key:'ellipsis'},this.props.customEllipsis?this.props.customEllipsis:'\u2026'));},render:function(){var p=!!n&&!this.props.disableNative,q=l(this.props.className,"_4ik4"+(p?' '+"_4ik5":'')),r=this.props.children,s={};if(this.props.lineHeight)s={height:this.props.lineHeight*this.props.lines,lineHeight:this.props.lineHeight+'px'};if(p){s[n]=this.props.lines;}else{q=l(q,'clearfix');r=[h.createElement('div',{className:"_4ik6",key:'inner'},r),this._renderEllipsis()];}return (h.createElement('div',{className:q,style:s},r));}});f.exports=o;},null);
__d("d3/time/month",["d3/time/day","d3/time/interval"],function a(b,c,d,e,f,g,h){if(c.__markCompiled)c.__markCompiled();var i=c("d3\/time\/interval")._interval,j=i(function(k){k=h(k);k.setDate(1);return k;},function(k,l){k.setMonth(k.getMonth()+l);},function(k){return k.getMonth();});j.s=j.range;j.s.utc=j.utc.range;f.exports=j;},null);
__d('PrettyNum',['InsightsNumUtils'],function a(b,c,d,e,f,g,h){if(c.__markCompiled)c.__markCompiled();function i(j,k,l,m){'use strict';this.radix=k||10;if(typeof j==='number'){this.value=j;}else this.value=parseFloat(j,this.radix);this.effective=m||2;if(l||l===0){this.precision=l;}else this.precision=this.$PrettyNum1();}i.prototype.$PrettyNum1=function(){'use strict';if(this.value%1===0)return 0;var j=parseInt(this.value,this.radix);if(j!==0)return 2;var k=Math.abs(this.value%1);return this.effective-Math.ceil(Math.log(k)/Math.log(this.radix));};i.prototype.toPretty=function(){'use strict';if(this.precision===0){var j=parseInt(this.value,10);return this.longForm?h.prettyInt(j):h.prettyShortInt(j);}else return h.prettyFloat(parseFloat(this.value.toFixed(this.precision),this.radix));};i.prototype.toPrettyPercentage=function(){'use strict';var j=this.value*100;return h.prettyFloat(parseFloat(j.toFixed(this.precision),this.radix))+'%';};i.prototype.toPrettyCurrency=function(j){'use strict';if(this.precision===0){return h.prettyShortCurrency(j,this.value);}else return h.prettyCurrency(j,this.value);};i.prototype.enableLongForm=function(){'use strict';this.longForm=true;return this;};f.exports=i;},null);
__d('Sprite.art',['getStyleProperty'],function a(b,c,d,e,f,g,h){'use strict';if(c.__markCompiled)c.__markCompiled();var i={},j=null,k=/url\(([^)]*)\)/;function l(o){var p=o.match(k);return p?p[1]:null;}function m(o){return parseFloat(o)||null;}function n(o){var p=o?o.split(' '):[];if(p.length!=2)return [null,null];return [m(p[0]),m(p[1])];}f.exports={get:function(o){if(o in i)return i[o];if(!j)j=document.createElement('i');j.className=o;document.body.appendChild(j);var p=h(j,'backgroundImage'),q=h(j,'backgroundSize'),r=h(j,'backgroundPosition'),s=h(j,'width'),t=h(j,'height');document.body.removeChild(j);return i[o]={boxSize:[m(s),m(t)],imageSize:n(q),offset:n(r),uri:l(p)};}};},null);
__d('CSSBackgroundPattern.art',['Sprite.art'],function a(b,c,d,e,f,g,h){'use strict';if(c.__markCompiled)c.__markCompiled();function i(j){this.$CSSBackgroundPattern1=j;}i.prototype.applyFill=function(j){var k=h.get(this.$CSSBackgroundPattern1),l=k.uri,m=k.boxSize[0],n=k.boxSize[1],o=k.offset[0],p=k.offset[1];if(m===null||n===null)j.fillImage(l,m,n,o,p);};f.exports=i;},null);
__d('SpectrumConstants',[],function a(b,c,d,e,f,g){'use strict';if(c.__markCompiled)c.__markCompiled();var h={plotBands:{LabelPosition:{BOTTOM_LEFT:'bottom left',BOTTOM_RIGHT:'bottom right',TOP_LEFT:'top left',TOP_RIGHT:'top right'}},xAxis:{defaultTickCount:10,defaultTickSize:4,defaultTickPadding:3},vlines:{defaultLineCount:10}};f.exports=h;},null);
__d("SpectrumEnvironment",[],function a(b,c,d,e,f,g){if(c.__markCompiled)c.__markCompiled();var h={ignoreUserEvents:false};f.exports=h;},null);
__d('SpectrumBaseStyleSheet',['SpectrumBaseStyleSheet-upstream','cx'],function a(b,c,d,e,f,g,h,i){if(c.__markCompiled)c.__markCompiled();h.areas.partialOverlayClass="_4v0s";f.exports=h;},null);
__d('FeedPlaceHolderStory.react',['Locale','React','XUICard.react','cx','joinClasses'],function a(b,c,d,e,f,g,h,i,j,k,l){if(c.__markCompiled)c.__markCompiled();var m=i.createClass({displayName:'FeedPlaceHolderStory',render:function(){return (i.createElement(j,{className:l("_2iwp",this.props.className)},i.createElement('div',{className:(h.isRTL()?"direction_rtl":'')+(' '+"_2iwo")},i.createElement('div',{className:"_2iwq"},i.createElement('div',{className:"_2iwr"}),i.createElement('div',{className:"_2iws"}),i.createElement('div',{className:"_2iwt"}),i.createElement('div',{className:"_2iwu"}),i.createElement('div',{className:"_2iwv"}),i.createElement('div',{className:"_2iww"}),i.createElement('div',{className:"_2iwx"}),i.createElement('div',{className:"_2iwy"}),i.createElement('div',{className:"_2iwz"}),i.createElement('div',{className:"_2iw-"}),i.createElement('div',{className:"_2iw_"}),i.createElement('div',{className:"_2ix0"})))));}});f.exports=m;},null);
__d("XAYMTMultiTipAsyncClickController",["XController"],function a(b,c,d,e,f,g){c.__markCompiled&&c.__markCompiled();f.exports=c("XController").create("\/ads\/growth\/aymt\/multi_async_click\/",{tip_id:{type:"String",required:true},channel_id:{type:"String",required:true},target:{type:"String",required:true}});},null);
__d("XAYMTMultiTipEligibilityLoggerAsyncController",["XController"],function a(b,c,d,e,f,g){c.__markCompiled&&c.__markCompiled();f.exports=c("XController").create("\/ads\/growth\/aymt\/log\/eligibility\/",{tip_id:{type:"String",required:true},channel_id:{type:"String",required:true}});},null);