/*!CK:1271066618!*//*1453237321,*/

if (self.CavalryLogger) { CavalryLogger.start_js(["tz5ul"]); }

__d("BrowseAsyncPagingType",[],function a(b,c,d,e,f,g){c.__markCompiled&&c.__markCompiled();f.exports={SCROLL:"scroll",PAGINATE:"paginate"};},null);
__d('BoostedPostDialogButtonWrapper.react',['BoostedPostDialogButton.react','React'],function a(b,c,d,e,f,g,h,i){if(c.__markCompiled)c.__markCompiled();var j=i.PropTypes,k=i.createClass({displayName:'BoostedPostDialogButtonWrapper',propTypes:{data:j.shape({buttonID:j.string.isRequired,configData:j.object.isRequired,displaySection:j.string.displaySection}),placement:j.string.isRequired,customLinkLabelReact:j.object,onUpsellButtonClick:j.func},render:function(){var l=this.props.data;if(!l)return i.createElement('span',null);return (i.createElement('div',{id:l.buttonID},i.createElement(h,{buttonID:l.buttonID,configData:l.configData,customLinkLabelReact:this.props.customLinkLabelReact,displaySection:l.displaySection,placement:this.props.placement,onUpsellButtonClick:this.props.onUpsellButtonClick})));}});f.exports=k;},null);
__d('FBMorePager.react',['OnVisible.react','React','cx','getViewportDimensions','throttle'],function a(b,c,d,e,f,g,h,i,j,k,l){if(c.__markCompiled)c.__markCompiled();var m,n;'use strict';m=babelHelpers.inherits(o,i.Component);n=m&&m.prototype;function o(q,r){n.constructor.call(this,q,r);this.state={isMounted:false,throttledCallback:l((function(){return this.$FBMorePager1();}).bind(this),q.throttle),visible:false};}o.prototype.componentWillReceiveProps=function(q){this.$FBMorePager2(q);if(this.props.throttle!==q.throttle)this.setState({throttledCallback:l((function(){return this.$FBMorePager1();}).bind(this),q.throttle)});};o.prototype.componentWillMount=function(){this.setState({isMounted:true});};o.prototype.componentWillUnmount=function(){this.setState({isMounted:false});};o.prototype.render=function(){return (i.createElement('div',{className:"_3fv0"+(this.state.visible?' '+"_3fv1":'')},i.createElement(h,{buffer:this.props.buffer,onVisible:(function(){return this.$FBMorePager3();}).bind(this),ref:'onVisible'},this.props.children)));};o.prototype.$FBMorePager2=function(){this.setState({visible:false});this.refs.onVisible&&this.refs.onVisible.reset();};o.prototype.$FBMorePager3=function(){this.setState({visible:true});this.state.throttledCallback();};o.prototype.$FBMorePager1=function(){this.state.isMounted&&this.props.onMore&&this.props.onMore();};var p=Math.min(k().height,k().width)*2;o.defaultProps={buffer:p,throttle:1000};f.exports=o;},null);
__d('ExplicitRegistrationReactDispatcher',['ExplicitRegistrationDispatcher','ReactDOM'],function a(b,c,d,e,f,g,h,i){if(c.__markCompiled)c.__markCompiled();var j,k;'use strict';j=babelHelpers.inherits(l,h);k=j&&j.prototype;l.prototype.dispatch=function(m){i.unstable_batchedUpdates((function(){k.dispatch.call(this,m);}).bind(this));};function l(){j.apply(this,arguments);}f.exports=l;},null);
__d('timeString',['fbt'],function a(b,c,d,e,f,g,h){if(c.__markCompiled)c.__markCompiled();function i(j,k){k=k||Date.now();var l='',m=null,n=Math.floor((k-j)/1000);if(n<10){l=h._("just now");}else if(n<60){l=h._("a few seconds ago");}else if(n<60*2){l=h._("about a minute ago");}else if(n<3600){m=Math.floor(n/60);l=h._("{number} minutes ago",[h.param('number',m)]);}else if(n<3600*2){l=h._("about an hour ago");}else if(n<3600*24){m=Math.floor(n/3600);l=h._("{number} hours ago",[h.param('number',m)]);}else if(n<3600*24*2){l=h._("about a day ago");}else if(n<3600*24*30){m=Math.floor(n/3600/24);l=h._("{number} days ago",[h.param('number',m)]);}else if(n<3600*24*30*2){l=h._("about a month ago");}else if(n<3600*24*30*12){m=Math.floor(n/3600/24/30);l=h._("{number} months ago",[h.param('number',m)]);}else if(n<3600*24*30*24){l=h._("over a year ago");}else{m=Math.floor(n/3600/24/365);l=h._("{number} years ago",[h.param('number',m)]);}return l;}f.exports=i;},null);
__d('SubscriptionList',['invariant'],function a(b,c,d,e,f,g,h){if(c.__markCompiled)c.__markCompiled();function i(j,k){'use strict';this.$SubscriptionList1=[];this.$SubscriptionList2=j;this.$SubscriptionList3=k;}i.prototype.$SubscriptionList4=function(j){'use strict';var k=this.$SubscriptionList1.indexOf(j);!(k!==-1)?h(0):undefined;this.$SubscriptionList1.splice(k,1);if(this.$SubscriptionList1.length===0)this.$SubscriptionList3.call(this);};i.prototype.add=function(j){'use strict';var k={callback:j};this.$SubscriptionList1.push(k);if(this.$SubscriptionList1.length===1)this.$SubscriptionList2.call(this);return {remove:this.$SubscriptionList4.bind(this,k)};};i.prototype.getCallbacks=function(){'use strict';return this.$SubscriptionList1.map(function(j){return j.callback;});};i.prototype.fireCallbacks=function(){'use strict';for(var j=arguments.length,k=Array(j),l=0;l<j;l++)k[l]=arguments[l];this.$SubscriptionList1.forEach(function(m){m.callback.apply(null,k);});};f.exports=i;},null);
__d('StaticSearchSource',['AbstractSearchSource','SearchSourceCallbackManager','TokenizeUtil'],function a(b,c,d,e,f,g,h,i,j){if(c.__markCompiled)c.__markCompiled();var k,l;k=babelHelpers.inherits(m,h);l=k&&k.prototype;function m(n,o){'use strict';l.constructor.call(this);this.$StaticSearchSource1=n;this.$StaticSearchSource2=new i({parseFn:j.parse,matchFn:j.isQueryMatch,indexFn:o});this.$StaticSearchSource2.addLocalEntries(this.$StaticSearchSource1);}m.prototype.searchImpl=function(n,o,p){'use strict';if(!n){o(this.$StaticSearchSource1,n);}else this.$StaticSearchSource2.search(n,o,p);};f.exports=m;},null);
__d("XBoostedComponentFetchButtonDataController",["XController"],function a(b,c,d,e,f,g){c.__markCompiled&&c.__markCompiled();f.exports=c("XController").create("\/ads\/boosted_components\/fetch_button_data\/",{app_id:{type:"Int",required:true},page_id:{type:"Int",required:true},post_id:{type:"Int"},ref:{type:"String",required:true}});},null);
__d("XTopChartsRootPageController",["XController"],function a(b,c,d,e,f,g){c.__markCompiled&&c.__markCompiled();f.exports=c("XController").create("\/places\/",{city_query:{type:"String"}});},null);